#!/bin/bash
#This is to use doris for coregistration.
#actually, the reason for this is that I didn't figure out how to do it using ISCE when the ifgs are generated by topsApp J
#anyway... it works
NOPROCESSORS=24
WORKDIR=`pwd`

#find Master DIRectory as to be in the middle of the set (should be done better, but for SB no big deal..)
ls 2*_*/merged -d >tmp.tmp
TMPX=`cat tmp.tmp | wc -l`
let TMPY=$TMPX/2
MDIR=`tail -n +$TMPY tmp.tmp | head -n1 | cut -d '/' -f1`
rm tmp.tmp
echo "Converting the ISCE-based files into doris way"
for x in `ls 2*_*/merged -d | cut -d '/' -f1`; do
 if [ $MDIR == $x ]; then
   ln -s `pwd`/$MDIR/merged/topophase.flat.full `pwd`/$MDIR/merged/resampled.raw
  else
   sentineloshka_prepare_doris.sh $MDIR $x
 fi
done
echo "Dorissing"

#first we will parallelize processing of doris: coarse and fine coregistration
for x in `ls 2*_*/merged -d | cut -d '/' -f1`; do
 #if the coregistration wasn't performed well, retry it - this is useful if we rerun the doris processing..
 if [ `ls $x/merged/coreg.out -al | gawk {'print $5'}` -lt 10000 ]; then
  rm $x/merged/coreg.out 2>/dev/null
 fi 2>/dev/null
 echo $x >> tmpifg
 if [ ! $MDIR == $x ]; then
  sed '/COREGPM/d' $x/merged/coreg.dorisin > $x/merged/corr.dorisin
  sed -i '/RESAMPLE/d' $x/merged/corr.dorisin
  sed '/FINE/d' $x/merged/corr.dorisin > $x/merged/corr.coarse.dorisin
  sed '/COARSECORR/d' $x/merged/corr.dorisin > $x/merged/corr.fine.dorisin  
  A=`pwd`/$x/merged
  W=`pwd`
  let NOPROCSKORO=$NOPROCESSORS-1
  while [ `pidof doris | wc -w` -gt $NOPROCSKORO ]; do echo "Fully working"; sleep 10;	done
  cd $A
  nohup doris corr.coarse.dorisin 2>corr.err && cd $W && sentineloshka_correct_coarsecorr.sh $x && cd $A && nohup doris corr.fine.dorisin 2>corr.fine.err &
  cd $W
  sleep 2
 fi
done

while [ `pidof doris | wc -l` -gt 0 ]; do echo "Waiting for doris.."; sleep 10; done

rm tmpifg

#now this coregpm and resampling - i will not parallelize since it is mainly about writing data..
echo "Computing coregistration polynomial"
for x in `ls 2*_*/merged/coreg.dorisin -d | cut -d '/' -f1`; do
  sed '/COARSECORR/d' $x/merged/coreg.dorisin > $x/merged/coreg2.dorisin
  sed -i '/FINE/d' $x/merged/coreg2.dorisin
  sed '/RESAMPLE/d' $x/merged/coreg2.dorisin  > $x/merged/coregpm.dorisin
  doris $x/merged/coregpm.dorisin >/dev/null 2>/dev/null
  sleep 2
  if [ `grep -c End_comp $x/merged/coreg.out` -eq 0 ]; then 
    doris $x/merged/coregpm.dorisin
  fi
  sed '/COREGPM/d' $x/merged/coreg2.dorisin  > $x/merged/coreg.resample.dorisin
  echo "Resampling interferogram "$x
  doris $x/merged/coreg.resample.dorisin >/dev/null 2>/dev/null
  touch $x/merged/resampled.done
done

#Checking doris results, removing wrong ones
for x in `ls 2*_*/merged -d | cut -d '/' -f1`; do
 MSIZE=`ls -al $MDIR/merged/topophase.flat.full | gawk {'print $5'}`
 SSIZE=`ls -al $x/merged/resampled.raw 2>/dev/null | gawk {'print $5'}`
 if [ ! $MDIR == $x ]; then
  if [ ! $MSIZE -eq $SSIZE ]; then
   echo "Not good.. some error occured in "$x
   rm $x/merged/resampled.raw
  else
   echo "Interferogram "$x" ready"
  fi 2>/dev/null
 fi
done
echo "Interferogramming finished"
echo " "
cd $WORKDIR
touch sentineloshka_finished

#The upper code is super stupid but there was a lot of problems trying to start doris in background, for a parallel approach :(
# a pity.. i will need to rebuild this totally
